### PR TITLE
Add file size

### PR DESCRIPTION
**Pull request by AliciadW**

### CODE REVIEW

**Comment by longhotsummer** [comment]
Nice :) I haven't checked what it looks like -- do you think it's worth making it grey with text-muted, or does it look sufficiently different given the red link and the black text?

**Comment by AliciadW** [comment]
With text-muted it looks like this:
Screenshot 2019-03-12 at 12 08 27


As I had it originally it looks like this:
Screenshot 2019-03-12 at 12 09 31

**Comment by longhotsummer** [comment]
Let's go with muted, please. Can we also lose the whitespace between the brackets and the numbers.

**Comment by longhotsummer** [comment]
@AliciadW sorry, pls also ensure the size isn't part of the link.

**Comment by AliciadW** [comment]
@longhotsummer updated :-)

**Pull request merged**
